language: objective-c

before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet

install:
   - pod repo update
   - pod install

osx_image: xcode10.1

xcode_sdk: iphonesimulator12.1

script:
  - set -o pipefail
  - xcodebuild -showsdks
  - xcodebuild -workspace Sunrise.xcworkspace -scheme "Sunrise Prod" -destination "platform=iOS Simulator,name=iPhone SE" clean build build-for-testing | xcpretty -c;
  - xcodebuild -workspace Sunrise.xcworkspace -scheme "Sunrise Prod" -destination "platform=iOS Simulator,name=iPhone SE" test-without-building | xcpretty -c;