language: objective-c

osx_image: xcode7.3

xcode_sdk: iphonesimulator9.3

script: xcodebuild -workspace Sunrise.xcworkspace -scheme "Sunrise Staging" -destination "platform=iOS Simulator,name=iPhone 6" test
